networks:
  default: rinkeby-fork
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.2.0"
      - "openzeppelin-contracts-08=OpenZeppelin/openzeppelin-contracts@4.0.0/contracts"
